apiVersion: apps/v1
kind: Deployment
metadata:
  name: appserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      labels:
        app: appserver
    spec:
      containers:
      - name: appserver
        image: tomcat:latest
        ports:
        - containerPort: 8080